STATES_DATA = [
    {"code": "AL", "name": "Alabama", "agency": "Alabama Department of Corrections (ADOC)", "right_to_work": True},
    {"code": "AK", "name": "Alaska", "agency": "Alaska Department of Corrections", "right_to_work": False},
    {"code": "AZ", "name": "Arizona", "agency": "Arizona Department of Corrections, Rehabilitation and Reentry (ADCRR)", "right_to_work": True},
    {"code": "AR", "name": "Arkansas", "agency": "Arkansas Division of Correction (ADC)", "right_to_work": True},
    {"code": "CA", "name": "California", "agency": "California Department of Corrections and Rehabilitation (CDCR)", "right_to_work": False},
    {"code": "CO", "name": "Colorado", "agency": "Colorado Department of Corrections (CDOC)", "right_to_work": False},
    {"code": "CT", "name": "Connecticut", "agency": "Connecticut Department of Correction (CT DOC)", "right_to_work": False},
    {"code": "DE", "name": "Delaware", "agency": "Delaware Department of Correction (DOC)", "right_to_work": False},
    {"code": "FL", "name": "Florida", "agency": "Florida Department of Corrections (FDC)", "right_to_work": True},
    {"code": "GA", "name": "Georgia", "agency": "Georgia Department of Corrections (GDC)", "right_to_work": True},
    {"code": "HI", "name": "Hawaii", "agency": "Hawaii Department of Corrections and Rehabilitation (DCR)", "right_to_work": False},
    {"code": "ID", "name": "Idaho", "agency": "Idaho Department of Correction (IDOC)", "right_to_work": True},
    {"code": "IL", "name": "Illinois", "agency": "Illinois Department of Corrections (IDOC)", "right_to_work": False},
    {"code": "IN", "name": "Indiana", "agency": "Indiana Department of Correction (IDOC)", "right_to_work": True},
    {"code": "IA", "name": "Iowa", "agency": "Iowa Department of Corrections (IDOC)", "right_to_work": True},
    {"code": "KS", "name": "Kansas", "agency": "Kansas Department of Corrections (KDOC)", "right_to_work": True},
    {"code": "KY", "name": "Kentucky", "agency": "Kentucky Department of Corrections (DOC)", "right_to_work": True},
    {"code": "LA", "name": "Louisiana", "agency": "Louisiana Department of Public Safety and Corrections (DPS&C)", "right_to_work": True},
    {"code": "ME", "name": "Maine", "agency": "Maine Department of Corrections (MDOC)", "right_to_work": False},
    {"code": "MD", "name": "Maryland", "agency": "Maryland Department of Public Safety and Correctional Services (DPSCS)", "right_to_work": False},
    {"code": "MA", "name": "Massachusetts", "agency": "Massachusetts Department of Correction (MADOC)", "right_to_work": False},
    {"code": "MI", "name": "Michigan", "agency": "Michigan Department of Corrections (MDOC)", "right_to_work": False},
    {"code": "MN", "name": "Minnesota", "agency": "Minnesota Department of Corrections (MNDOC)", "right_to_work": False},
    {"code": "MS", "name": "Mississippi", "agency": "Mississippi Department of Corrections (MDOC)", "right_to_work": True},
    {"code": "MO", "name": "Missouri", "agency": "Missouri Department of Corrections (MODOC)", "right_to_work": False},
    {"code": "MT", "name": "Montana", "agency": "Montana Department of Corrections (MT DOC)", "right_to_work": False},
    {"code": "NE", "name": "Nebraska", "agency": "Nebraska Department of Correctional Services (NDCS)", "right_to_work": True},
    {"code": "NV", "name": "Nevada", "agency": "Nevada Department of Corrections (NDOC)", "right_to_work": True},
    {"code": "NH", "name": "New Hampshire", "agency": "New Hampshire Department of Corrections (NHDOC)", "right_to_work": False},
    {"code": "NJ", "name": "New Jersey", "agency": "New Jersey Department of Corrections (NJDOC)", "right_to_work": False},
    {"code": "NM", "name": "New Mexico", "agency": "New Mexico Corrections Department (NMCD)", "right_to_work": False},
    {"code": "NY", "name": "New York", "agency": "New York State Department of Corrections and Community Supervision (DOCCS)", "right_to_work": False},
    {"code": "NC", "name": "North Carolina", "agency": "North Carolina Department of Adult Correction (NCDAC)", "right_to_work": True},
    {"code": "ND", "name": "North Dakota", "agency": "North Dakota Department of Corrections and Rehabilitation (DOCR)", "right_to_work": True},
    {"code": "OH", "name": "Ohio", "agency": "Ohio Department of Rehabilitation and Correction (ODRC)", "right_to_work": False},
    {"code": "OK", "name": "Oklahoma", "agency": "Oklahoma Department of Corrections (ODOC)", "right_to_work": True},
    {"code": "OR", "name": "Oregon", "agency": "Oregon Department of Corrections (ODOC)", "right_to_work": False},
    {"code": "PA", "name": "Pennsylvania", "agency": "Pennsylvania Department of Corrections (PADOC)", "right_to_work": False},
    {"code": "RI", "name": "Rhode Island", "agency": "Rhode Island Department of Corrections (RIDOC)", "right_to_work": False},
    {"code": "SC", "name": "South Carolina", "agency": "South Carolina Department of Corrections (SCDC)", "right_to_work": True},
    {"code": "SD", "name": "South Dakota", "agency": "South Dakota Department of Corrections (DOC)", "right_to_work": True},
    {"code": "TN", "name": "Tennessee", "agency": "Tennessee Department of Correction (TDOC)", "right_to_work": True},
    {"code": "TX", "name": "Texas", "agency": "Texas Department of Criminal Justice (TDCJ)", "right_to_work": True},
    {"code": "UT", "name": "Utah", "agency": "Utah Department of Corrections (UDC)", "right_to_work": True},
    {"code": "VT", "name": "Vermont", "agency": "Vermont Department of Corrections (VDOC)", "right_to_work": False},
    {"code": "VA", "name": "Virginia", "agency": "Virginia Department of Corrections (VADOC)", "right_to_work": True},
    {"code": "WA", "name": "Washington", "agency": "Washington State Department of Corrections (WADOC)", "right_to_work": False},
    {"code": "WV", "name": "West Virginia", "agency": "West Virginia Division of Corrections and Rehabilitation (WVDCR)", "right_to_work": True},
    {"code": "WI", "name": "Wisconsin", "agency": "Wisconsin Department of Corrections (DOC)", "right_to_work": True},
    {"code": "WY", "name": "Wyoming", "agency": "Wyoming Department of Corrections (WDOC)", "right_to_work": True},
]
